# SPDX-FileCopyrightText: Copyright (c) 2026 Massachusetts Institute of Technology
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
channel0:
  basic_network:
    dst_port: 60134 # UDP destination port for packets
  packet:
    num_samples: 6393750
    spoof_header: true
    packet_skip_bytes: 64
    header_metadata:
      start_sample_idx: 0
      sample_rate_numerator: 63937500
      sample_rate_denominator: 1
      freq_idx: 31650
      num_subchannels: 1
      pkt_samples: 2048
      bits_per_int: 16
      is_complex: 1
  resampler0:
    up: 1
    down: 31
    outrate_cutoff: 1.0
    outrate_transition_width: 1.90303
    attenuation_db: 103
  resampler1:
    up: 1
    down: 5
    outrate_cutoff: 1.0
    outrate_transition_width: 1.51515
    attenuation_db: 103
  resampler2:
    up: 8
    down: 33
    outrate_cutoff: 1.0
    outrate_transition_width: 0.2
    attenuation_db: 99.725
  spectrogram_mqtt:
    service_name: recorder_fft_ch000
  spectrogram_output:
    plot_subdir: spectrograms/ch000
  drf_sink:
    channel_dir: simone/ch000

channel1:
  enabled: false
  pipeline:
    spectrogram: false
  basic_network:
    dst_port: 60133 # UDP destination port for packets
  spectrogram_mqtt:
    service_name: recorder_fft_ch001
  spectrogram_output:
    plot_subdir: spectrograms/ch001
  drf_sink:
    channel_dir: simone/ch001
