# SPDX-FileCopyrightText: Copyright (c) 2026 Massachusetts Institute of Technology
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
channel0:
  pipeline:
    spec_resampler: false
    spectrogram: false
  basic_network:
    dst_port: 60134 # UDP destination port for packets
  resampler0:
    up: 1
    down: 32
    outrate_cutoff: 1.0
    # transition_width: 2 * (cutoff - 1 / remaining_dec)
    #                   2 * (1.0 - 1 / 20) = 1.9
    outrate_transition_width: 1.9
    attenuation_db: 102.5
  drf_sink:
    channel_dir: simone/ch000

channel1:
  enabled: true
  pipeline:
    spec_resampler: false
    spectrogram: false
  basic_network:
    dst_port: 60133 # UDP destination port for packets
  resampler0:
    up: 1
    down: 32
    outrate_cutoff: 1.0
    # transition_width: 2 * (cutoff - 1 / remaining_dec)
    #                   2 * (1.0 - 1 / 20) = 1.9
    outrate_transition_width: 1.9
    attenuation_db: 102.5
  drf_sink:
    channel_dir: simone/ch001
